# Change baseurl before deploy
baseurl = "https://christt105.github.io"
languageCode = "en-us"
title = "Christian Mart√≠nez De La Rosa"
timeZone = "Europe/Madrid"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[pagination]
pagerSize = 5